In [12]:
import pandas as pd
import dash
from dash import html, dcc
from dash.dependencies import Input, Output, State
import plotly.graph_objects as go
import plotly.express as px
from dash import no_update
import datetime as dt

In [13]:
#Create App
app = dash.Dash(__name__)

#Clear the layout and do not display exception till callback gets executed
app.config.suppress_callback_exceptions = True

#Read the wildfire data into pandas dataframe
df=pd.read_csv('Historical_Wildfires.csv')

In [14]:
df.head()

,Region,Date,Estimated_fire_area,Mean_estimated_fire_brightness,Mean_estimated_fire_radiative_power,Mean_confidence,Std_confidence,Var_confidence,Count,Replaced
0,NSW,1/4/2005,8.68000,312.266667,42.400000,78.666667,2.886751,8.333333,3,R
1,NSW,1/5/2005,16.61125,322.475000,62.362500,85.500000,8.088793,65.428571,8,R
2,NSW,1/6/2005,5.52000,325.266667,38.400000,78.333333,3.214550,10.333333,3,R
3,NSW,1/7/2005,6.26400,313.870000,33.800000,92.200000,7.529940,56.700000,5,R
4,NSW,1/8/2005,5.40000,337.383333,122.533333,91.000000,7.937254,63.000000,3,R

In [15]:
#Extract year and month from the date column
df['Month'] = pd.to_datetime(df['Date']).dt.month_name() #Used for the names of months
df['Year'] = pd.to_datetime(df['Date']).dt.year

In [16]:
df.head()

,Region,Date,Estimated_fire_area,Mean_estimated_fire_brightness,Mean_estimated_fire_radiative_power,Mean_confidence,Std_confidence,Var_confidence,Count,Replaced,Month,Year
0,NSW,1/4/2005,8.68000,312.266667,42.400000,78.666667,2.886751,8.333333,3,R,January,2005
1,NSW,1/5/2005,16.61125,322.475000,62.362500,85.500000,8.088793,65.428571,8,R,January,2005
2,NSW,1/6/2005,5.52000,325.266667,38.400000,78.333333,3.214550,10.333333,3,R,January,2005
3,NSW,1/7/2005,6.26400,313.870000,33.800000,92.200000,7.529940,56.700000,5,R,January,2005
4,NSW,1/8/2005,5.40000,337.383333,122.533333,91.000000,7.937254,63.000000,3,R,January,2005

### Layout Section of Dash

In [17]:
# Add title to the dashboard
app.layout = html.Div(children=[
    html.H1("WildFires in Australia",
            style={'textAlign': 'center', 'color': '#503D36', 'font-size': 26}),
    # Add the radio items and a dropdown right below the first inner division #outer division starts
    html.Div([
        # First inner division for adding dropdown helper text for Selected Drive wheels
        html.Div([
            html.H2('Select Region:', style={'margin-right': '2em'}),
            # Radio items to select the region
            dcc.RadioItems(['NSW', 'QL', 'SA', 'TA', 'VI', 'WA'], 'NSW', id='region', inline=True)
        ], style={'display': 'flex', 'alignItems': 'center', 'justifyContent': 'center'}),

        html.Div([
            html.H2('Select Year:', style={'margin-right': '2em'}),
            dcc.Dropdown(df['Year'].unique(), value=2005, id='year')
            # Notice the use of unique() from pandas to fetch the values of year from the dataframe for dropdown
        ], style={'display': 'flex', 'alignItems': 'center', 'justifyContent': 'center'}),

        html.Div([
            html.H2('Select Month:', style={'margin-right': '2em'}),
            dcc.Dropdown(['All'] + list(df['Month'].unique()), value='All', id='month')
        ], style={'display': 'flex', 'alignItems': 'center', 'justifyContent': 'center'}),

        html.Div([
            html.Div([], id='plot1'),
            html.Div([], id='plot2')
        ], style={'display': 'flex', 'flexDirection': 'column', 'alignItems': 'center'}),
    ]),
])

In [18]:
# Add the Output and input components inside the app.callback decorator.
@app.callback(
    [Output(component_id='plot1', component_property='children'),
     Output(component_id='plot2', component_property='children')],
    [Input(component_id='region', component_property='value'),
     Input(component_id='year', component_property='value'),
     Input(component_id='month', component_property='value')]
)
# Add the callback function.
def reg_year_display(input_region, input_year, input_month):
    # Filter data
    region_data = df[df['Region'] == input_region]
    y_r_data = region_data[region_data['Year'] == input_year]
    
    # Calculate total estimated fire area for the entire year
    total_est_area = y_r_data['Estimated_fire_area'].sum()

    if input_month == 'All':
        # Plot pie chart for the whole year
        est_data = y_r_data.groupby('Month')['Estimated_fire_area'].sum().reset_index()
        fig1 = px.pie(est_data, values='Estimated_fire_area', names='Month',
                      title="{} : Estimated Fire Area Distribution for Year {}".format(input_region, input_year),
                      hole=0.3, color_discrete_sequence=px.colors.qualitative.Pastel)
        fig1.update_traces(pull=[0.1] * len(est_data), textinfo='percent+label', marker=dict(line=dict(color='#000000', width=2)))
        fig1.update_layout(annotations=[dict(text='Fire Area', x=0.5, y=0.5, font_size=20, showarrow=False)])
    else:
        # Filter data for the selected month
        m_data = y_r_data[y_r_data['Month'] == input_month]

        # Check if there's no data for the selected filters
        if m_data.empty:
            return [html.Div("No data available for the selected region, year, and month.", style={'color': 'red'}),
                    html.Div()]

        # Calculate total estimated fire area for the selected month
        month_est_area = m_data['Estimated_fire_area'].sum()

        # Plot pie chart for the selected month
        fig1 = go.Figure(data=[go.Pie(labels=['Selected Month', 'Rest of the Year'],
                                      values=[month_est_area, total_est_area - month_est_area],
                                      pull=[0.1, 0],
                                      hole=0.3)])
        fig1.update_layout(title="{} : Estimated Fire Area in {} as Percentage of Year {}".format(input_region, input_month, input_year),
                           annotations=[dict(text='Fire Area', x=0.5, y=0.5, font_size=20, showarrow=False)])

    # Plot two - Monthly Average Count of Pixels for Presumed Vegetation Fires
    veg_data = y_r_data.groupby('Month')['Count'].mean().reset_index()
    fig2 = px.bar(veg_data, x='Month', y='Count',
                  title='{} : Average Count of Pixels for Presumed Vegetation Fires in year {}'.format(input_region,
                                                                                                        input_year),
                  color='Count', color_continuous_scale='Viridis')
    fig2.update_layout(xaxis_title='Month', yaxis_title='Average Count', plot_bgcolor='#f0f0f0')
    fig2.update_traces(marker_line_color='rgb(8,48,107)', marker_line_width=1.5, opacity=0.6)

    return [dcc.Graph(figure=fig1),
            dcc.Graph(figure=fig2)]


if __name__ == '__main__':
    app.run_server(port=8090)